apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-proxy
  namespace: istio-system
  labels:
    release: kube-prometheus-stack-1765177684
spec:
  selector:
    matchLabels:
      istio: sidecar
  namespaceSelector:
    any: true
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  namespace: istio-system
  labels:
    release: kube-prometheus-stack-1765177684
spec:
  selector:
    matchLabels:
      app: istiod
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-monitoring
      interval: 15s
